### ISSUE TITLE
Melhorar pacotes de módulos com pastas para cada um. Adicionar para cada módulo um ErrorBoundary para erros específicos.

### ISSUE THREAD

**Issue by fr3d3rico** [fr3d3rico/frontend-titanic#8]

**Comment by fr3d3rico** [comment]
Vou criar uma pasta para cada módulo. Por exemplo, "login", "home", "about".
E ao criar a issue, a princípio, estava pensando em criar um arquivo ErrorBoundary em cada uma dessas novas pastas. Agora me veio a idéia de criar um pasta separada chamada "utils" e criar este ErrorBoundary para ser utilizado pelos outros módulos.

**Comment by fr3d3rico** [comment]
Alterado e comitado.

**Comment by mmitsunaga** [comment]
Tá cagando no Titanic né ? Kkkk


Em seg, 4 de jan de 2021 15:38, Fred <notifications@github.com> escreveu:
